import type { Metadata } from "next";
import NavbarComp from "@/Components/Navbar";
import "./globals.scss";
import { Poppins } from "next/font/google";
import PrelineScript from "@/Components/PrelineScript";

const poppins = Poppins({ weight: ["500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrelineScript />
      <body className={poppins.className}>
        <NavbarComp />
        {children}
      </body>
    </html>
  );
}
